site_name: Exploration du Web
site_description: Cours participatif sur le Web.
site_author: Etudiants participant au cours.
nav:
  - Home: index.md
  - Cours:
      - cours/html.md
      - cours/javascript.md
      - cours/deepweb.md
      - Sessions précédentes: cours/index.md
  - Contribuer:
      - Définir le contenu : contribuer/contenu.md
      - Comment réaliser du contenu : contribuer/realiser.md
      - Comment progresser : contribuer/progresser.md
      - Les outils utilisés: contribuer/outils.md
  - Déroulé:
      - Séance 1: deroule/seance1.md
      - Séance 2: deroule/seance2.md
      - Séance 3: deroule/seance3.md
      - Séance 4: deroule/seance4.md
      - Séance 5: deroule/seance5.md
      - Séance 6: deroule/seance6.md

  - A propos: about/about.md

extra_css: [extra.css]

copyright: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
